services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend-ng
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend