import numpy as np

from backend.algorithms import self_adaptive_es
from backend.algorithms.params.self_adaptive_es_params import SelfAdaptiveESParams
from backend.structure.protein import Protein

AAs = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']

def log(msg: str):
    with open('log.txt', 'a') as f:
        f.write(msg + '\n')
    print(msg)

for n in [10, 50, 100, 200, 500, 1000, 1500]:
    seq = ''.join([np.random.choice(AAs) for _ in range(n)])
    log(f"[n={n}] {seq}")
    for ff in ['amber', 'charmm']:
        log(f"  {ff}:")
        Protein.TIME_STRUCTURE = []
        Protein.TIME_CIF = []
        Protein.TIME_FITNESS = []

        params = SelfAdaptiveESParams(generations=5, force_field=ff, population_size=100, children_size=600, sigma=36)
        es = self_adaptive_es.SelfAdaptiveES(params)
        es.run(seq)
        t_structure = np.array(Protein.TIME_STRUCTURE)
        t_cif = np.array(Protein.TIME_CIF)
        t_fitness = np.array(Protein.TIME_FITNESS)

        log(f"{np.median(t_structure)},{np.median(t_cif)},{np.median(t_fitness)}")
        #print("f,min,max,mean,median,std,samples")
        #print(f"structure, {t_structure.min()}, {t_structure.max()}, {t_structure.mean()}, {np.median(t_structure)}, {t_structure.std()}, {t_structure.shape[0]}")
        #print(f"cif, {t_cif.min()}, {t_cif.max()}, {t_cif.mean()}, {np.median(t_cif)}, {t_cif.std()}, {t_cif.shape[0]}")
        #print(f"fitness, {t_fitness.min()}, {t_fitness.max()}, {t_fitness.mean()}, {np.median(t_fitness)}, {t_fitness.std()}, {t_fitness.shape[0]}")

# second run with perf_counter
# YKQNRMVGKT
# EQIGGNAHKMDLHHAFAQCIVAGTVIKGDGQHFHCMHSQMNIPYGLYDVT
# VVHIQKAELVQNMWSGPHWSHSNVPTHDQYRVPVGNWWNAQCNPQSGHWWQTHWGHISFWWFAFNHRYLMYEELERLFYDSVLNGHLHCKQCNMHGALNH
# DVNESIEDVCTFGRLPQDLCSFLMVKAETCYYGDVIELQCDLFKVRYHYNLAHMQPKQAICYMMWIEHIALDKPFSHPVAQRTVRAMWPMWLWCECPKIRGIWIWIKVPEHGVNLERDVLDYCEVDMGLGYFVLWKYPFHLIHNGDESTDYLFSFSIDRTFEVAPNCSYWIHDNEANSENIGWYVGFNQKCKTKFVQDMW
# GYTQWALRCENCMKKFSAGCPEPVNRNQQCFKTGNDRMSRYQQRIKYIIGCMFQSEFIKMKNGSGMRMAIPSIGFEQWFEHAISPHLGHMVGFTWMLHNDGQLHWRDISEAYSDNCLFWMLQYYGPQIHTKMKMHVTSVFMTQPDMFAENREFPHWNTWTEFMMYRFPIRWKDCDYYHNQWLTHVSENIEKQFSIIVKPHKVGEDLHTADDSQHCSYQAACPLMLFCWYLQYGQNAFNEITKIARITFPWRWYWCNYWKIIKVPAPASVPMHYLSYMCEPTCTCEYHLWPCCYMVIFSDDGLSMHTATNHKFIEACIDPETKGMALWMVHYCFYDMYWMYHRRPELNRAAESNYLPRDAGKVMALWMFFIYYSDAYEYCQEMQLVFLKLKVPCVKAYINHDGSRFENKNQELAQQIPSIVSDCAKAEFKHRQIDPSFWTHIVRIARVITHAMTCKSQTWFTMDTRPNGYLIYCNSAWCCEWIDFNGHTACKNLMIAEIWS
# YHWSCDRQVHGKNDGCLWNVEPIDTHMDWLTPAVQPFPSDPSMETTMILQTCVNMCSAHSEGHPVWIKRFQLRQGWHCITTFYAEQQPATHKDQHASKWIWWFSEPFTFQYKRGTQSYRQAVNPNLIMTTVHGDRATDWISTCWLEWCFYISKPMQAVWNSGTYYLTNRMRPELSLENEDWVCHMQYMCRSVLQRLHRGIPDRCCWTMTQSEGMTDKCQVEQCQQGRTYHMDSAEAVMYGEPKCCRYCMMLSWTCKVQSCGADQQLNSKSTTKYCWIQCRFTILPGRRQNMKQVWRYAQPQKIPFDTENYFLYSAIHEIVLDSNQAAKARRANLGHSMRCDCNWHEGEHPRAGSITQTDLECDNNEEYWNMVHGNGCPCFDQRGAVMRETEENNQHYDDMPFIQDMPGDQDWPRFRHILHSACGVRWNKASLLIVPDKYTTKYSYIHVRPTIYDAGYYSIMNTIYWEAMRVARWQVDYMMPLPIATVHTAWKTSGMPSFHKNCDRCERRYLAIDHHGDFWCVIFWWLFYHGVAEISALDCRVNMGWTFDEPCKEVGKWIGSPKCACKKQRVLFHPDMVDFYDDHWHPCVMQYNQSNWYNGWDHTNNHHWHVEHMNNCNWKDMMGLAELMMSIQGVNKSVMGLRYALVCAGGYQGKWRMRFGWHFWTLDYEMIQRREPSARRTFEIQRNRTHLNKCDISDWMHTRDQMISTYWYPELKNSLMVIFSNADAWKGVHHHFWICDWPMSVVQYLENFYQNYLTVTSLMSWQEPRGFYGEEFQQYGSRYKFDKQWDRFSLMKENLALESMCFMISRGSNMCMCQCKMSGLFHEYCCCQFVMTMTLKYVKNYFQPHFHKKGEMEDRQVPYNHDIAEFIHTRYQKGMTPVMGHLNLTQFWCRYRPYPNQTQVQCNNRPKRFLGNLRICEYHLEHRYARDKLMPLFYQQYWYFALFQWMLERCIKAFCCRYSENHCEMHWDRPHHNCHRLRSSLAVLDDPHARWCTVI
# RYCPSGSGHDKKQLMWRRGFYDPTSGCRDGWARRCHPFRDSIWIGIWYGHIWNFCNSDSSVPTVKGWPIVPPEGTQVDAMPKSLLGFYEKFFWHGNGGFHICNFIVFGFEWGWEWPNELAAVDRMEDKEAHYHAIAGFLQFCTMNCGFDIWPFTAWLEPADLVYYVHNTHRLYEQRASGEIAFCMQMETRYMFGFPRRNMMFAIPMRFKTFAIYPHLNFRLKYGCNIHARQWHCASVFARYYWRCWTAMAERPYGIWHPNFKALSYGSLMYHGCCSEQVYKRTDVWMMAQFIKGMMIMLDRWWMIPITMFTLTSKCNVMIAGGHEDVALMTGKFTPIFMHPCHLVQFTFVWSSCTWMPVYSWRQQMLYLDAIMWFLVVGLYAKNHGSHQLARTRPNRQSTWMWYEGYEMIPCTNRNCIRTLNPDWCVIRHMTVIQTFDTQTDDSPVFKCGPYTWPLDYYCDIQDMFMADQLEMETNIIHQPECELGAPAFQHHLNSEGIDNENVIPSLPFNPGQDAVEWSDFCWSNQYHAWYFSSWNVHEVPFWNKQEIAFMWADWSWPRNMTDIVHKMVIEHGDKVNVDFVVHFAHRFMMNNCKDWATHHWMGYPQRFAFRKGIMTHENRGHQTMIRCKFMADWDNAMRYDKTFHLSALHTSSKHSYIWEAAAQDCEYDERIHDMDKKTASDPFRRAQPLQIHEAQMMHLIDGAVWTEHETCFVPMAWFRYNNRSTASYHYRGSQFKERRHGKQMADVYAHHASCAKHWDHIMGKPKMMPESDWQWIEWHGAKPACDLRLHIICPWYGHEGRDLMSCVAPQYRDQNWGWQWKAIEGIMIAEYYCKMEMPQDIITPMLWVTYMMHRTQSGVFDNLWDYDEHPPFMPDPTHYDMVQGMCMWSMIANYYDNVLCSKAKSCPWAQADKYCMSIYLAKVYPEWRLMKLWFIAYRCKRESISVNNEEIKQNYWLRAVCTAFGGDAMGRHMPEMATCTVPAMHDPHMQTIQRNAAMHHGIKKRNFAIHTACACGISIFSANAAREGQDRPTSLYYIQFMPQKVRTGGQMHHMHVFPDCIDFARIHREDCSDIIAEDEYDMQHNKNDYEAYWMNCQLSFTKWKVQKGEYRGQGEAPCCMFMTVTFASYTNTHSAYLSWMAIHYIMTSFNNHFGTVGFCARCGRYPLWPIDYWRQGCNSEYEWPMNYQIILKHAIGSAQYIIQSLMSHWMRTICGSKRTVWFQIEMMTAKPWYQMGYRDLDWCGMTPYTSCEMGWHGVFSWCCQAPGSVATRDRAPWKIMIQTIAWWLNQRPFFGLNLACSHQLDTTDELGSIKYSTDPIEYWRSGLNTSGPPRQEVTTGRPKDGVKAQFMYNYRIEYEAMLTERYEADRSDKMCKWYWLWECIRGNWWWVFQDGMNKGHVETKEEPPRDYPSVCRLCHFHCNYPWDSQLRSEDWMKHYCVPRLVRVIVYTRRECRKYSCWDVTDTGAACVLDTCWPTEADPMHNNTPIGLTITYNDM

# n:         [10, 50, 100, 200, 500, 1000, 1500]
# amber
# structure: [1727958.5, 8376145.5, 17105250, 32246562.5, 81716104.5, 163035875, 243419833.5]
# cif:       [362458, 1513916.5, 3284625, 6162021, 15719229, 32110375, 48292667]
# fitness:   [2720437.5, 8382792, 17191187.5, 32153729.5, 82789562.5, 176910792, 267918771]
# charmm
# structure: [1713708.5, 8379645.5, 16845520.5, 32282187, 81673416.5, 162273708, 243257604]
# cif:       [358917, 1513604, 3248604.5, 6162083.5, 15809667, 32090770.5, 48771333]
# fitness:   [2875500, 8694625, 17478833.5, 34009396, 92645333.5, 191938187, 299282187.5]

# first run with process_time
# WTWRNPWYIT
# REGLIDYWKDFYIGWRRTNLHCHAVAAHEKCFCCFADELVYDAIMGESWT
# VGVPTAMLRAPHEKPGGLIGETPFFHDSWHTKHWNCPGRCNQPHPGQYQVTDCWTHKGLTLLFTGRQDTDPVGCEFKQRCKNYRQPVGCKHQSPQFEDRH
# TNVHNGPPHMQRYIQPMTELNDTDTNCSLMAWRPRRFTSQNPSQCPTNVLTTYDHYAMSAVIFMLCGIFPYIAWGMPLNRASWRHYILHVPICAYVTVLDVCYIWPQDSNEACLGTPPQSDHHNKITTLEFFHPRTSNTMPEARLLVLMKALLFLDSGGQYVATNFKVLHCFQCCGCSHAAWCINQQFWTTHLQKMTAEI
# TKLFSAIALHQAWGDVSAWWSYYYPYMWMEQQPPDAEPQGILGHGYGKWELNHWIDLTPDPPRFLMNPDLPNPIYADYQMINCQFVVGASKTINCYGVMCHRVECDGRTVNQPNQPHDKYKPHNKAMMWGQCSMIQLLSKAGNNNAVLYERQEIAFCINVKLEIKWWDKLGHWHYCLQYANCCQYTAFACHLIHFKQSARMGQYELDEDKILGCMDAKPDQMENIREFWVAKAYEHIAWRPNYEWPYWVWDIEQHCGTEAFQYWPTDGWTRHLGGRHHWLIMAFIGQENCFSHKMCNSDHGQFPNPKVNNSLGFPFTQIGPINVGTEQIQCRIPFHPPIWLSSYVPRWPHGRLFPMPEKDFKYQNLSLPNLGNWCRRSLFRRMGSGSCNPTDNELVCTASSQMPNLQEVLYPFATFKHRERYPQLISVPETVFAYGSMDRQCSYVRIKGLPDPLCTTDHWKGSAMCKQCENAQKKCNSPKRPTMLHKMFRQCVMKKCTGK
# RMQSDDPEPQDPWFSITFRSAPLCWIILVGWQCECKIQIWFYGSFASRRMMANARDARTFMDCWYITWEFMSKDIAEADKFSGNKPMCDKKRDIRPQKDTHEMMDLTRDCQTHTSIDCAKVYNRHSEKVDQSTMWDLRMFIWAWDAYRMWKCNMLLAHQPTLKFTAVQCMYWEQWVWGQMDLRMLFELGERITAASMCTVTGFYSHACNRRRGCHYYIGFAQDYYFQSARGMDAESLYYYIHNMCRIVHLLFMPFFWDPFHNHETTFQNICGCYYEGRDPYACHQCFRPRIVSLNSQATQEHFSMTSLFCAPWTNCITYTFDQNWAFGASGMARAVYMFYGSFGVTNTEDHYYGLPTQRWRCRHVHFEQFQPDKIMREWCADELVFWTGLVAFRDVPSFRNMRVLGFIASSIEYAVFNSQELDCIILCKKHRCDDKFKAFAVLLTADTNRQEYMGWTDMIYLWLIYFTEPICLAEPDFSSGMKQFISFDGGWALINHFIHTWYAHQICEVVVVYHEPSSQMRYNIFNIVRIEPRFQEMCGIRGWEFRHPTRIDQPIMCMQKKIIYALGHEHERPDEYADWNWREMLEEFPIYPGYKLLIFQVAEREHDNCAGVKEFQVVLPRWTISLLPTWMILPIAGNRGLRFYRPRCLGSSPSKNTMWHYWVTGFIPEIQFIIYSSSQDMTDICKEIWNAFQCNSLRRIHIDGMESWVAVWGEEAKGPRFCNHFLNMHCGKHGMQCLQCMVPWNAVWMERNTGDNMINTYPDHYNKDTALDWDLATPQLSCSAGAVDIIFINVGDPFAQYVRVMTDIYKWETSDNNYFLCVMQCWWGFITNKSQAVGGTMNTAEGSDVTSYVVLHGAWCTQYFKFADRACRFNKFEVRCVRKAKHCENVEVCGSHWFANDGDWFRVDGYTWLGPSESQYFMCNTGGTKDSMYYCLIRMNKGWAHTMPSVNPYEQNWAGCQATDYLCSIEHAVGTTAPSATAQTGQVWWVAHNDNQPCG
# PLIHGKTDLAWTEEFYFGDWKNPPMTPHWQCDPIHMCTDMRRQGLAILRKKTGPGPAWEELTWLSSHGRMFVTFEPGNEEFCNMRQMARNLLAMYFGYNVADRQQENFNYFMAPLHILRCDSGAVHYFMGIVKRLPAYEYYWWDEPCMYHYPVQSHLTQGQWIFKYPRECLDQGWFEFKFAPKVVKLLAHMSRDEDTAMQWAFVRLTGNGEEKHLILVCVEKAPALMAEPMEGEYGADQFMESVKEMKYAQLQVYLMQVKDESCEYHMGSPTSTNWVVPNKIILWEGYRDKSSWQSQIKTTCDMRKIKPTDFAAGQCYLQDHDPWFALEAMDILKKLACWCYWGFRSQEGGQQQTRIIFSWLTEKGGNPFLMMSTHGPGTFQDDLTEPRMDRYNQSRKIWGICRPTGYERLDIFCINPMWTPVAQRCIDCLRSADIFGQMLPGVLNIPGGPKMICQTATARIGDAISSYIIYYWSFWNMLRLYTLRWCVFDIPHCLLSPLFTSQYWPTYLFPVRETCMYKNWRQAQIYAQMLFVFYCWNQCQAFNWGSYLVKFYAVFVFSNAMQCLINWEVTTFRLSNQIIHFMTPQNLGMKKAAINWSMFWSQPQQFIGINACGQSYNSCRADKPDMSKTSGAAVQCLARRFNCVFTSMEIEPATIFRMGAIIPPDETWAECGLCHAWDQSRIKHMFMNHFGACVAIILITRVGMTHKFNFRNRIDKEHRVAKSLAERHRPLQRDLCIENGMACVCDMNFIRMSSGDKQASNIQPYYVYKIKEPRKGNTCEFLWYVHTHKHGTEQIKEGIVADKWTHELVLKCFHGGYLTMIRFCILDQIFPYQYCFMVSWPDNFRAMPLFRLNGSVFEVHGSEERSNCCLGSFGTLMSYAKKKFKHMRSTWTIVEQICFNFSFKDQDLLPDLQYYCCYGQTFWQGKHSKRVLTWHMFTNQDPVFNTYSCTTAIVSFGMEDMHGTHVGIMNTCDMEDMMMVCKVIGLRFMQYMMSFRTVKLRPRNFQLQADSRDYQDQDLRSDSHWTKNIDRRNWWKHSVYTASYRWELTNEWEHMNPVTQCYKYPRFDSRLQASLRQFNLAASQYCAHICYLKTNGFSPRHEWDPRYVTNNHNFVIHDASADQIAPGHSNKFFWHSPLSYPWPSYEECYRTHDPQGDDMWPMVKKAIESHLQNQCNDKVEMSNNLAKGIPVQLYINSNRSFNQRPYQFLVQRSQKKHIAHTRWFSYKTNINTEDVQLPCVRWEPDPHFCFDAGMSTPCHVVEDARYEWNETCGHWVCNFMYISCVHPKKAVTIIPCTVDMNAFFSLRGKAFAVHFRFACLETYDSTWQKVLKCQLLHAFPRLNWCCKTMIKMMAERVQAGLWHGQSMDNMPGPTEPILTPFLFWDIEPYWLLRDKCMGDPAPIRYGFDHYWNPIALQFWEEWYDWTIFNYQQSCKDISVASMSSLNWSDLPLLVWWYNNGDMGMCCWHAQTHCRCYIEMPTCKQSTAVPDFWVPESKE

# n:         [10, 50, 100, 200, 500, 1000, 1500]
# amber
# structure: [1738500, 8499000, 16774000, 31886000, 81314000, 162741000, 242989500]
# cif:       [384000, 1596000, 3181000, 5986000, 15378000, 31525000, 48004500]
# fitness:   [2249000, 8298000, 15641500, 29512500, 76054000, 156573500, 240314000]
# charmm
# structure: [1733000, 8446000, 15800000, 31934000, 80735000, 163045000, 242786500]
# cif:       [383000, 1590500, 3010000, 5969000, 15434000, 31731500, 48464000]
# fitness:   [2271000, 8272000, 14588000, 29570000, 76396000, 157241500, 239851000]